export const ADD_BOOK = 'ADD_BOOK';
export const DELETE_BOOK = 'DELETE_BOOK';
export const UPDATE_BOOK = 'UPDATE_BOOK';

export const ADD_BOOK_TO_CART = 'ADD_BOOK_TO_CART';
export const DELETE_BOOK_FROM_CART = 'DELETE_BOOK_FROM_CART';
export const DELETE_ALL_FROM_CART = 'DELETE_ALL_FROM_CART';
export const UPDATE_BOOK_IN_CART = 'UPDATE_BOOK_IN_CART';

export const GET_BOOKS = 'GET_ALL_BOOKS';
export const GET_ALL_BOOKS_FROM_CART = 'GET_ALL_BOOKS_FROM_CART';